### ISSUE TITLE
set up Kanban board

### ISSUE THREAD

**Issue by ahzia** [ahzia/Space-Travelers#25]
Hello,
We have configured the kanban board for our project, kindly Review it:
[Project Link](https://github.com/ahzia/Space-Travelers/projects/1)
We are three Students in the Team: @ahzia , @Rustamxon7 , @Kossi-stack

**Comment by EricMbouwe** [comment]
### Hello team,

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlight!
- Good PR

# Required Changes ♻️

- [x] Make sure all cards are assigned to team members. You have 3 cards without any assignees, let's fix that.

![Screenshot from 2021-10-11 12-03-00](https://user-images.githubusercontent.com/40503704/136780046-51658aaa-dc15-4d7d-a23a-29631250b0d9.png)


_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:

- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

---

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by ahzia** [comment]
@EricMbouwe Thanks for mentioning assigned the remaining tasks.

**Comment by EricMbouwe** [comment]
### Hi @ahzia, @Rustamxon7 and @Kossi-stack, 

# Status: Approved ✔️
Excellent job on this project. Keep it up 👏
Your project is complete! There is nothing else to say other than... it's time to merge it 💪
Congratulations! 🎉

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by ahzia** [comment]
@EricMbouwe Thanks For Approving.
